name: Deploy

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout source
        run: git clone git@github.com:quintalcg/quintalcg.git source

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: source/frontend/package-lock.json

      - run: npm ci
        working-directory: source/frontend

      - run: npm run build
        working-directory: source/frontend

      - uses: actions/upload-pages-artifact@v3
        with:
          path: source/frontend/dist

      - id: deploy
        uses: actions/deploy-pages@v4
